### PR TITLE
Sanjay add validation for email and phone number

### PR DESCRIPTION
**Pull request by SanjaySargam**

### CODE REVIEW

**Comment by SanjaySargam** [comment]
Hii@ayush-agarwal-190, why this issue excluded from hacktoberfest ?

**Comment by ayush-agarwal-190** [comment]
> Hii@ayush-agarwal-190, why this issue excluded from hacktoberfest ?

can you please send me the screen shot

**Comment by SanjaySargam** [comment]
> > Hii@ayush-agarwal-190, why this issue excluded from hacktoberfest ?
> 
> can you please send me the screen shot

**Comment by SanjaySargam** [comment]
> > Hii@ayush-agarwal-190, why this issue excluded from hacktoberfest ?
> 
> can you please send me the screen shot

Screenshot 2022-10-01 121350

**Comment by SanjaySargam** [comment]
> > Hii@ayush-agarwal-190, why this issue excluded from hacktoberfest ?
> 
> can you please send me the screen shot

I think you didn't closed this issue. That's why it's showing like this

**Pull request merged**
